#NetworkInterfaces 要素の定義に誤りがあったため、スタックの作成に失敗したテンプレート
AWSTemplateFormatVersion: "2010-09-09"
Description: "Udemy CloudFormation Training for EC2"
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-08b5b3a93ed654d19"
      InstanceType: "t2.micro"
      KeyName: "xxxx" #★実際に利用するキーペア名に書き換えること
      AvailabilityZone: "us-east-1a"
      SecurityGroupIds:
        - "xxxx" #★実際に利用するセキュリティグループIDに書き換えること
      NetworkInterfaces: #ENIの設定
        - DeviceIndex: 0 #NetworkInterfacesを設定する場合、DeviceIndexの設定は必須
        - AssociatePublicIpAddress: true #パブリックIPの付与
        - SubnetId: "xxxx" #★実際に利用するサブネットIDに書き換えること