AWSTemplateFormatVersion: '2010-09-09'
Description: Udemy CloudFormation Training for Lambda

Resources:
  #CloudWatch LogsとDynamoへのアクセス許可ロール
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:  #ロールの信頼ポリシー
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      
      Policies: #ロールの許可ポリシー
        - PolicyName: "TrainingLambdaPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:*"
                Resource:
                  - arn:aws:logs:*:*:*
              
              - Effect: "Allow"
                Action:
                  - "dynamodb:*"
                Resource:
                  - "*"





